//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OrderDetail
    {
        public long Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual tb_Order tb_Order { get; set; }
        public virtual tb_Product tb_Product { get; set; }
    }
}
