//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Product()
        {
            this.tb_OrderDetail = new HashSet<tb_OrderDetail>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> ProductDate { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Description { get; set; }
    
        public virtual tb_Category tb_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OrderDetail> tb_OrderDetail { get; set; }
    }
}
